### ISSUE TITLE
Update to Laravel Meta

### ISSUE THREAD

**Issue by bobmulder** [kodeine/laravel-meta#63]
This library looks great, and a feature like this is definitely needed in Laravel. However, no commit has been done since 2 years ago.

What about updating this package to make it stable and ready for production for Laravel applications of these days?

**Comment by kodeine** [comment]
It is stable, I'll add a tag

**Comment by bobmulder** [comment]
Thank you for your response. However, I'd say the following things should be done:

- [ ] **must have**: an update to Laravel 5.8
- [ ] **must have**: whole package should be tested (till then the package is not stable)
- [ ] **optionally**: define a default migration
- [ ] **optionally**: artisan command to generate migrations for custom models (like `posts_meta`)

**Comment by kodeine** [comment]
@bobmulder can you please send me a PR request? I'd be happy to merge that in.

**Comment by bobmulder** [comment]
I'll think about it @kodeine, I need to make a decision about what library/implementation to use for meta data in Laravel. Not sure yet if I'll use (and contribute to) this library...
